=== alt83/mvp4g/trunk/xsd/mvp4g-conf.xsd
<?xml version="1.0" encoding="UTF-8" ?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<xs:simpleType name="boolean">
		<xs:restriction base="xs:boolean">
			<xs:pattern value="true|false" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="package">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="className">
		<xs:restriction base="xs:string">
			<xs:pattern value=".?[a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*" />
		</xs:restriction>
	</xs:simpleType>
	
	<xs:simpleType name="eventObjectClass">
		<xs:restriction base="xs:string">
			<xs:pattern value="([a-zA-Z][a-zA-Z0-9_]*(\.[a-zA-Z][a-zA-Z0-9_]*)*) || []" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="name">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*" />
		</xs:restriction>
	</xs:simpleType>

	<xs:simpleType name="nameArray">
		<xs:restriction base="xs:string">
			<xs:pattern value="[a-zA-Z][a-zA-Z0-9_]*(\s?,\s?[a-zA-Z][a-zA-Z0-9_]*)*" />
		</xs:restriction>
	</xs:simpleType>
	

	<xs:attributeGroup name="simpleMpv4gElement">
		<xs:attribute name="name" type="name" use="required" />
		<xs:attribute name="class" type="xs:NMTOKEN" use="required" />
	</xs:attributeGroup>

	<xs:attributeGroup name="mvp4gElementWithServices">
		<xs:attributeGroup ref="simpleMpv4gElement" />
		<xs:attribute name="services" type="nameArray" use="optional" />
	</xs:attributeGroup>
	

	<xs:element name="views">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="view" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="services">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="service" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="childModules">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="childModule" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
			<xs:attribute name="beforeEvent" type="name" use="optional" />
			<xs:attribute name="afterEvent" type="name" use="optional" />
			<xs:attribute name="errorEvent" type="name" use="optional" />
		</xs:complexType>
	</xs:element>
			
	<xs:element name="childModule">
		<xs:complexType>
			<xs:attributeGroup ref="simpleMvp4gElement" />
			<xs:attribute name="async" type="xs:boolean" use="false" />
			<xs:attribute name="autoDisplay" type="xs:boolean" use="false" />
			<xs:attribute name="eventToDisplayView" type="name" use="true" />
		</xs:complexType>
	</xs:element>
	
	<xs:element name="history">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="converter" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
			<xs:attribute name="initEvent" type="name" use="optional" />
			<xs:attribute name="initEvent" type="name" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="presenters">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="presenter" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
			<xs:attribute name="package" type="package" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="events">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="event" minOccurs="1" maxOccurs="unbounded" />
			</xs:sequence>
		</xs:complexType>
	</xs:element>

	<xs:element name="converter">
		<xs:complexType>
			<xs:attributeGroup ref="mvp4gElementWithServices" />
		</xs:complexType>
	</xs:element>

	<xs:element name="event">
		<xs:complexType>
			<xs:attribute name="handlers" type="nameArray" use="optional" />
			<xs:attribute name="type" type="name" use="required" />
			<xs:attribute name="calledMethod" type="name" use="optional" />
			<xs:attribute name="eventObjectClass" type="package" use="optional" />
			<xs:attribute name="history" type="name" use="optional" />
			<xs:attribute name="forwardToParent" type="xs:boolean" use="optional" />
			<xs:attribute name="modulesToLoad" type="nameArray" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="mvp4g">
		<xs:complexType mixed="true">
			<xs:all>
				<xs:element ref="events" minOccurs="0"  />
				<xs:element ref="history" minOccurs="0" />
				<xs:element ref="presenters" />
				<xs:element ref="services" minOccurs="0" />
				<xs:element ref="start" minOccurs="0"  />
				<xs:element ref="views" minOccurs="0"  />
				<xs:element ref="childModules" minOccurs="0"  />
			</xs:all>
		</xs:complexType>
	</xs:element>

	<xs:element name="presenter">
		<xs:complexType>
			<xs:attributeGroup ref="mvp4gElementWithServices" />
			<xs:attribute name="view" type="name" use="required" />
		</xs:complexType>
	</xs:element>

	<xs:element name="service">
		<xs:complexType>
			<xs:attributeGroup ref="simpleMpv4gElement" />
			<xs:attribute name="path" type="xs:string" use="optional" />
			<xs:attribute name="generatedClassName" type="className" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="start">
		<xs:complexType>
			<xs:attribute name="view" type="name" use="required" />
			<xs:attribute name="eventType" type="name" use="optional" />
			<xs:attribute name="history" type="boolean" use="optional" />
		</xs:complexType>
	</xs:element>

	<xs:element name="view">
		<xs:complexType>
			<xs:attributeGroup ref="simpleMpv4gElement" />
		</xs:complexType>
	</xs:element>
	
</xs:schema>

=== alt83/mvp4g/trunk/examples/Mvp4gModules/src/xmlConfig/company-mvp4g.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.0.0/xsd/mvp4g-conf.xsd">
	<views package="com.mvp4g.example.client.company.view" >
		<view name="rootView" class="CompanyRootView" />
		<view name="listView" class="CompanyListView" />
		<view name="displayView" class="CompanyDisplayView"/>
		<view name="editView" class="CompanyEditView"/>
		<view name="creationView" class="CompanyCreationView"/>
	</views>
	<services package="com.mvp4g.example.client.company" >
		<service name="service" class="CompanyService" />
	</services>
	<presenters package="com.mvp4g.example.client.company.presenter" >
		<presenter name="rootPresenter" class="CompanyRootPresenter" view="rootView" />
		<presenter name="listPresenter" class="CompanyListPresenter" view="listView" services="service" />
		<presenter name="displayPresenter" class="CompanyDisplayPresenter" view="displayView" services="service" />
		<presenter name="editPresenter" class="CompanyEditPresenter" view="editView"  services="service" />			
		<presenter name="creationPresenter" class="CompanyCreationPresenter" view="creationView"  services="service" />
	</presenters>
	<events>
		<event type="goToCompany" handlers="listPresenter" />
		<event type="goToCreation" handlers="creationPresenter" />
		<event type="goToEdit" handlers="editPresenter" />
		<event type="goToDisplay" handlers="displayPresenter" />
		<event type="displayMessage" handlers="rootPresenter"/>
		<event type="companyCreated" handlers="listPresenter, displayPresenter"/>
		<event type="companyDeleted" handlers="listPresenter"/>		
	</events>
	
	<start view="rootView" />
	
</mvp4g>

=== alt83/mvp4g/tags/mvp4g-1.0.0/examples/Mvp4gPerformances/src/mvp4g-conf.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.0.0/xsd/mvp4g-conf.xsd">
	<views package="com.mvp4g.example.client">
		<view name="mainView" class="MainView" />
		<view name="testView" class=".presenters.TestMvp4gView" />		
	</views>	
		
	<presenters package="com.mvp4g.example.client">
		<presenter name="mainPresenter" class="MainPresenter" view="mainView" />
		
		<presenter name="handler1" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler2" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler3" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler4" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler5" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler6" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler7" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler8" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler9" class=".presenters.TestMvp4gPresenter" view="testView" />
		<presenter name="handler10" class=".presenters.TestMvp4gPresenter" view="testView" />
	</presenters>	
	
	<events>
		<event type="event1" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event2" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event3" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event4" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event5" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event6" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event7" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event8" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event9" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
		<event type="event10" handlers="handler1,handler2,handler3,handler4,handler5,handler6,handler7,handler8,handler9,handler10" />
	</events>

	<start view="mainView" />

</mvp4g>

=== alt83/mvp4g/trunk/examples/Mvp4gModulesXml/src/mvp4g-conf.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.0.0/xsd/mvp4g-conf.xsd">
	<childModules package="com.mvp4g.example.client" beforeEvent="beforeLoad" afterEvent="afterLoad" errorEvent="errorOnLoad">
		<childModule name="companyModule" class=".company.CompanyModule" eventToLoadView="changeBody"/>
		<childModule name="productModule" class=".product.ProductModule" eventToLoadView="changeBody" async="false" autoLoad="false"/>	
	</childModules>
	<views package="com.mvp4g.example.client.main" >
		<view name="rootView" class="MainView" />		
	</views>
	<presenters package="com.mvp4g.example.client.main" >
		<presenter name="rootPresenter" class="MainPresenter" view="rootView" />		
	</presenters>
	<events>
		<event type="goToCompany" handlers="" modulesToLoad="companyModule"/>
		<event type="goToProduct" handlers="" modulesToLoad="productModule" />
		<event type="changeBody" handlers="rootPresenter" />
		<event type="errorOnLoad" handlers="rootPresenter" />
		<event type="beforeLoad" handlers="rootPresenter"/>
		<event type="afterLoad" handlers="rootPresenter"/>
		<event type="displayMessage" handlers="rootPresenter"/>				
	</events>
	
	<start view="rootView" />
	
</mvp4g>

=== alt83/mvp4g/trunk/examples/Mvp4gModulesXml/src/xmlConfig/company-mvp4g.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.1.0/xsd/mvp4g-conf.xsd">
	<history package="com.mvp4g.example.client.company.historyConverter" >
		<converter name="companyHC" class="CompanyHistoryConverter"/>
	</history>
	<views package="com.mvp4g.example.client.company.view" >
		<view name="listView" class="CompanyListView" />
		<view name="displayView" class="CompanyDisplayView"/>
		<view name="editView" class="CompanyEditView"/>
		<view name="creationView" class="CompanyCreationView"/>
	</views>
	<services package="com.mvp4g.example.client.company" >
		<service name="service" class="CompanyService" />
	</services>
	<presenters package="com.mvp4g.example.client.company.presenter" >
		<presenter name="listPresenter" class="CompanyListPresenter" view="listView" services="service" />
		<presenter name="displayPresenter" class="CompanyDisplayPresenter" view="displayView" services="service" />
		<presenter name="editPresenter" class="CompanyEditPresenter" view="editView"  services="service" />			
		<presenter name="creationPresenter" class="CompanyCreationPresenter" view="creationView"  services="service" />
	</presenters>
	<events>
		<event type="goToCompany" handlers="listPresenter" />
		<event type="goToCreation" handlers="creationPresenter" />
		<event type="goToEdit" handlers="editPresenter" />
		<event type="goToDisplay" handlers="displayPresenter" history="companyHC"/>
		<event type="displayMessage" forwardToParent="true" eventObjectClass="java.lang.String"/>
		<event type="changeBody" eventObjectClass="com.google.gwt.user.client.ui.Widget" forwardToParent="true"/>
		<event type="companyCreated" handlers="listPresenter, displayPresenter"/>
		<event type="companyDeleted" handlers="listPresenter"/>
		<event type="selectCompanyMenu" forwardToParent="true" eventObjectClass=""/>		
	</events>
	
	<start view="listView" />
	
</mvp4g>

=== alt83/mvp4g/trunk/examples/EmployeeAdmin/src/mvp4g-conf.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/trunk/v1.0/src/xsd/mvp4g-conf.xsd">
	<views package="com.mvp4g.example.client.view" >
		<view name="rootTemplateView" class="RootTemplateView" />
		<view name="userListView" class="UserListView" />
		<view name="userProfileView" class="UserProfileView"/>
		<view name="userRoleView" class="UserRoleView"/>
	</views>
	<services package="com.mvp4g.example.client" >
		<service name="userService" class="UserService" />
	</services>
	<presenters package="com.mvp4g.example.client.presenter" >
		<presenter name="rootTemplate" class="RootTemplatePresenter" view="rootTemplateView" />
		<presenter name="userList" class="UserListPresenter" view="userListView" services="userService" />
		<presenter name="userProfile" class="UserProfilePresenter" view="userProfileView" services="userService" />
		<presenter name="userRole" class="UserRolePresenter" view="userRoleView"  services="userService" />			
	</presenters>
	<events>
		<event type="changeTopWidget" calledMethod="onChangeTopWidget" eventObjectClass="com.mvp4g.example.client.presenter.view_interface.widget_interface.MyWidgetInterface" handlers="rootTemplate" />
		<event type="changeLeftBottomWidget" calledMethod="onChangeLeftBottomWidget" eventObjectClass="com.mvp4g.example.client.presenter.view_interface.widget_interface.MyWidgetInterface" handlers="rootTemplate" />
		<event type="changeRightBottomWidget" calledMethod="onChangeRightBottomWidget" eventObjectClass="com.mvp4g.example.client.presenter.view_interface.widget_interface.MyWidgetInterface" handlers="rootTemplate" />
		
		<event type="createNewUser" calledMethod="onCreateNewUser" eventObjectClass="com.mvp4g.example.client.bean.UserBean" handlers="userProfile, userRole" />
		<event type="selectUser" calledMethod="onSelectUser" eventObjectClass="com.mvp4g.example.client.bean.UserBean" handlers="userProfile, userRole" />
		<event type="unselectUser" calledMethod="onUnselectUser" handlers="userProfile, userRole, userList" />
		<event type="userCreated" calledMethod="onUserCreated" eventObjectClass="com.mvp4g.example.client.bean.UserBean" handlers="userList" />
		<event type="userUpdated" calledMethod="onUserUpdated" eventObjectClass="com.mvp4g.example.client.bean.UserBean" handlers="userList, userRole" />
		
		<event type="start" calledMethod="onStart" handlers="userList, userProfile, userRole" />
		
	</events>
	
	<start view="rootTemplateView" eventType="start" />
	
</mvp4g>

=== alt83/mvp4g/examples/Mvp4gModulesXml/src/mvp4g-conf.xml
<?xml version="1.0" encoding="ISO-8859-1" ?>
<mvp4g xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="http://mvp4g.googlecode.com/svn/tags/mvp4g-1.0.0/xsd/mvp4g-conf.xsd">

	<debug enabled="true" />

	<childModules package="com.mvp4g.example.client" beforeEvent="beforeLoad" afterEvent="afterLoad" errorEvent="errorOnLoad">
		<childModule name="companyModule" class=".company.CompanyModule" eventToLoadView="changeBody"/>
		<childModule name="productModule" class=".product.ProductModule" eventToLoadView="changeBody" async="false" autoLoad="false"/>	
	</childModules>
	<history package="com.mvp4g.example.client.main.historyConverter" initEvent="start">
		<converter name="noParamHC" class="NoParamHistoryConverter"/>
	</history>
	<views package="com.mvp4g.example.client.main" >
		<view name="rootView" class="MainView" />		
	</views>	
	<presenters package="com.mvp4g.example.client.main" >
		<presenter name="rootPresenter" class="MainPresenter" view="rootView" />		
	</presenters>
	<events>
		<event type="goToCompany" handlers="" modulesToLoad="companyModule" history="noParamHC"/>
		<event type="goToProduct" handlers="" modulesToLoad="productModule" history="noParamHC" />
		<event type="changeBody" handlers="rootPresenter" />
		<event type="errorOnLoad" handlers="rootPresenter" />
		<event type="beforeLoad" handlers="rootPresenter"/>
		<event type="afterLoad" handlers="rootPresenter"/>
		<event type="displayMessage" handlers="rootPresenter"/>
		<event type="start" handlers="" />		
		<event type="selectCompanyMenu" handlers="rootPresenter"/>
		<event type="selectProductMenu" handlers="rootPresenter"/>		
	</events>
	
	<start view="rootView" history="true"/>
	
</mvp4g>
